### ISSUE TITLE
Incorporate portrait printing with Polaroid thermal printer

### ISSUE THREAD

**Issue by brannondorsey** [brangerbriz/emerge2016#3]

**Comment by brannondorsey** [comment]
- [x] Print to thermal printer via command line
- [x] Print to thermal printer via scripts incorporated into installation pipeline
- [x] Generate custom URL/id on the fly and overlay over printed image
- [x] Add `start_printer.sh` to `start_installation.sh`
- [x] Release `/dev/rfcomm0` in `stop_installation.sh`

**Comment by nbriz** [comment]
Done.
