### ISSUE TITLE
stop_installation.sh

### ISSUE THREAD

**Issue by nbriz** [brangerbriz/emerge2016#5]
Use pidfiles to keep track of what needs to be killed.

**Comment by brannondorsey** [comment]
Correct logging and pidfiles for:
- [x] SSH tunnel
- [x] MongoDB master
- [ ] ~~MongoDB slave~~
- [x] Kinect Daemon
- [x] lsyncd
- [x] ~~NodeWebkit App~~ (Not going to log or writing to pidfile after all as there are some complications, see NOTE in `bin/start_installation.sh. Automated shutdown is working however via a grep process in`bin/stop_installation.sh`).

**Comment by brannondorsey** [comment]
Done.
